Update Build AXT1800.yml

diff --git a/.github/workflows/Build AXT1800.yml b/.github/workflows/Build AXT1800.yml
--- a/.github/workflows/Build AXT1800.yml
+++ b/.github/workflows/Build AXT1800.yml
@@ -1,150 +1,227 @@
-CONFIG_TARGET_qualcommax=y
-CONFIG_TARGET_qualcommax_ipq60xx=y
-CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_glinet_gl-axt1800=y
-# CONFIG_COREMARK_ENABLE_MULTITHREADING is not set
-# CONFIG_COREMARK_NUMBER_OF_THREADS is not set
-# CONFIG_COREMARK_OPTIMIZE_O3 is not set
-CONFIG_HTOP_LMSENSORS=y
-CONFIG_LIBCURL_COOKIES=y
-CONFIG_LIBCURL_CRYPTO_AUTH=y
-CONFIG_LIBCURL_FILE=y
-CONFIG_LIBCURL_FTP=y
-CONFIG_LIBCURL_HTTP=y
-CONFIG_LIBCURL_HTTP2=y
-CONFIG_LIBCURL_OPENSSL=y
-CONFIG_LIBCURL_PROXY=y
-CONFIG_LIBCURL_TFTP=y
-CONFIG_LIBCURL_THREADED_RESOLVER=y
-CONFIG_LIBCURL_TLS_SRP=y
-CONFIG_LIBCURL_UNIX_SOCKETS=y
-CONFIG_LUCI_LANG_Hans=y
-# CONFIG_PACKAGE_bash is not set
-CONFIG_PACKAGE_bc=y
-CONFIG_PACKAGE_blkid=y
-CONFIG_PACKAGE_btrfs-progs=y
-# CONFIG_PACKAGE_coremark is not set
-CONFIG_PACKAGE_curl=y
-CONFIG_PACKAGE_default-settings=y
-CONFIG_PACKAGE_default-settings-chn=y
-CONFIG_PACKAGE_dosfstools=y
-CONFIG_PACKAGE_etherwake=y
-CONFIG_PACKAGE_exfat-fsck=y
-CONFIG_PACKAGE_exfat-mkfs=y
-CONFIG_PACKAGE_fancontrol=y
-CONFIG_PACKAGE_fdisk=y
-# CONFIG_PACKAGE_htop is not set
-# CONFIG_PACKAGE_ip-full is not set
-CONFIG_PACKAGE_iputils-arping=y
-CONFIG_PACKAGE_jq=y
-CONFIG_PACKAGE_kmod-crypto-acompress=y
-CONFIG_PACKAGE_kmod-crypto-blake2b=y
-CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
-CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
-CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
-CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
-CONFIG_PACKAGE_kmod-crypto-xxhash=y
-CONFIG_PACKAGE_kmod-fs-btrfs=y
-CONFIG_PACKAGE_kmod-fs-msdos=y
-CONFIG_PACKAGE_kmod-inet-diag=y
-CONFIG_PACKAGE_kmod-lib-lzo=y
-CONFIG_PACKAGE_kmod-lib-raid6=y
-CONFIG_PACKAGE_kmod-lib-xor=y
-CONFIG_PACKAGE_kmod-lib-xxhash=y
-CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
-CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
-CONFIG_PACKAGE_kmod-lib-zstd=y
-CONFIG_PACKAGE_kmod-nf-tproxy=y
-CONFIG_PACKAGE_kmod-nft-tproxy=y
-CONFIG_PACKAGE_kmod-nls-cp932=y
-CONFIG_PACKAGE_kmod-nls-cp936=y
-CONFIG_PACKAGE_kmod-nls-cp950=y
-CONFIG_PACKAGE_kmod-tcp-bbr=y
-CONFIG_PACKAGE_kmod-tun=y
-CONFIG_PACKAGE_kmod-usb-net-rtl8152-vendor=y
-CONFIG_PACKAGE_libattr=y
-CONFIG_PACKAGE_libbpf=y
-CONFIG_PACKAGE_libcap=y
-CONFIG_PACKAGE_libcap-ng=y
-CONFIG_PACKAGE_libcurl=y
-CONFIG_PACKAGE_libelf=y
-CONFIG_PACKAGE_libfdisk=y
-CONFIG_PACKAGE_liblua=y
-CONFIG_PACKAGE_liblucihttp-lua=y
-CONFIG_PACKAGE_liblzo=y
-CONFIG_PACKAGE_libmount=y
-CONFIG_PACKAGE_libncurses=y
-# CONFIG_PACKAGE_libnghttp2 is not set
-CONFIG_PACKAGE_libparted=y
-CONFIG_PACKAGE_libreadline=y
-# CONFIG_PACKAGE_libruby is not set
-CONFIG_PACKAGE_libstdcpp=y
-CONFIG_PACKAGE_libubus-lua=y
-# CONFIG_PACKAGE_libuv is not set
-CONFIG_PACKAGE_libwebsockets-full=y
-# CONFIG_PACKAGE_libyaml is not set
-CONFIG_PACKAGE_lsblk=y
-CONFIG_PACKAGE_lua=y
-CONFIG_PACKAGE_luci-app-argon-config=y
-CONFIG_PACKAGE_luci-app-autoreboot=y
-CONFIG_PACKAGE_luci-app-cpufreq=y
-CONFIG_PACKAGE_luci-app-diskman=y
-CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk=y
-CONFIG_PACKAGE_luci-app-fancontrol=y
-CONFIG_PACKAGE_luci-app-homeproxy=y
-# CONFIG_PACKAGE_luci-app-openclash is not set
-CONFIG_PACKAGE_luci-app-partexp=y
-CONFIG_PACKAGE_luci-app-ramfree=y
-# CONFIG_PACKAGE_luci-app-ttyd is not set
-CONFIG_PACKAGE_luci-app-turboacc=y
-# CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE_DRV is not set
-CONFIG_PACKAGE_luci-app-upnp=y
-CONFIG_PACKAGE_luci-compat=y
-CONFIG_PACKAGE_luci-i18n-argon-config=y
-CONFIG_PACKAGE_luci-i18n-autoreboot=y
-CONFIG_PACKAGE_luci-i18n-base=y
-CONFIG_PACKAGE_luci-i18n-cpufreq=y
-CONFIG_PACKAGE_luci-i18n-diskman=y
-CONFIG_PACKAGE_luci-i18n-fancontrol=y
-CONFIG_PACKAGE_luci-i18n-firewall=y
-CONFIG_PACKAGE_luci-i18n-homeproxy=y
-# CONFIG_PACKAGE_luci-i18n-openclash is not set (Удалено через make defconfig)
-CONFIG_PACKAGE_luci-i18n-package-manager=y
-CONFIG_PACKAGE_luci-i18n-partexp=y
-CONFIG_PACKAGE_luci-i18n-ramfree=y
-CONFIG_PACKAGE_luci-i18n-ttyd
-CONFIG_PACKAGE_luci-i18n-turboacc=y
-CONFIG_PACKAGE_luci-i18n-upnp=y
-CONFIG_PACKAGE_luci-lib-base=y
-CONFIG_PACKAGE_luci-lib-ip=y
-CONFIG_PACKAGE_luci-lib-jsonc=y
-CONFIG_PACKAGE_luci-lib-nixio=y
-CONFIG_PACKAGE_luci-lib-uqr=y
-CONFIG_PACKAGE_luci-lua-runtime=y
-CONFIG_PACKAGE_luci-theme-argon=y
-CONFIG_PACKAGE_miniupnpd-nftables=y
-# CONFIG_PACKAGE_openssh-client is not set
-# CONFIG_PACKAGE_openssh-keygen is not set
-CONFIG_PACKAGE_parted=y
-CONFIG_PACKAGE_resolveip=y
-# CONFIG_PACKAGE_ruby is not set
-# CONFIG_PACKAGE_ruby-bigdecimal is not set
-# CONFIG_PACKAGE_ruby-date is not set
-# CONFIG_PACKAGE_ruby-digest is not set
-# CONFIG_PACKAGE_ruby-enc is not set
-# CONFIG_PACKAGE_ruby-pstore is not set
-# CONFIG_PACKAGE_ruby-psych is not set
-# CONFIG_PACKAGE_ruby-stringio is not set
-# CONFIG_PACKAGE_ruby-yaml is not set
-CONFIG_PACKAGE_sing-box=y
-CONFIG_PACKAGE_sing-box-full=y
-CONFIG_PACKAGE_terminfo=y
-CONFIG_PACKAGE_ttyd=y
-CONFIG_PACKAGE_ucode-mod-lua=y
-CONFIG_PACKAGE_unzip=y
-# CONFIG_PACKAGE_v2dat is not set
-# CONFIG_PACKAGE_v2ray-geoip is not set
-# CONFIG_PACKAGE_v2ray-geosite is not set
-CONFIG_PARTED_READLINE=y
-# CONFIG_RUBY_ENABLE_YJIT is not set
-# CONFIG_PACKAGE_kmod-crypto-kpp is not set
-# CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set
+name: Build AXT-1800
+
+on:
+  #schedule:
+    #- cron: '0 16 * * *'
+  repository_dispatch:
+  workflow_dispatch:
+    inputs:
+      istore:
+        description: 'istore'
+        required: false
+        default: 'false'
+      docker:
+        description: 'Whether to build docker'
+        required: false
+        default: 'false'
+
+env:
+  REPO_URL_IMM: https://github.com/LiBwrt/openwrt-6.x
+  REPO_BRANCH: 24.10-6.12
+  FEEDS_CONF: feeds.conf.default
+  CONFIG_FILE_IMM: ./config/axt1800.config
+  DIY_P1_SH: ./sh/scripts-part1.sh
+  DIY_P2_SH: ./sh/scripts-part2.sh
+  DEFAULT_SETTING: ./default-settings
+  UPLOAD_BIN_DIR: true
+  UPLOAD_FIRMWARE: true
+  UPLOAD_RELEASE: true
+  CACHE_TOOLCHAIN: true
+  TZ: Asia/Shanghai
+
+jobs:
+  build:
+    runs-on: ubuntu-22.04
+    steps:
+    - name: Checkout
+      uses: actions/checkout@main
+
+    - name: "Optimize Disk Space"
+      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
+      with:
+        operate_sudo: "True"
+        general_include: ".+"
+        general_exclude: |-
+          ^GCC$
+          ^G\+\+$
+          Clang
+          LLVM
+        docker_include: ".+"
+        docker_prune: "True"
+        docker_clean: "True"
+        apt_prune: "True"
+        apt_clean: "True"
+        homebrew_prune: "True"
+        homebrew_clean: "True"
+        npm_prune: "True"
+        npm_clean: "True"
+        os_swap: "True"
+
+
+    - name: Install build dependencies
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
+          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
+          sudo -E apt-get -y update
+          sudo -E apt-get -y install $(curl -fsSL is.gd/depends_ubuntu_2204)
+          sudo -E systemctl daemon-reload
+          sudo -E apt-get -y autoremove --purge
+          sudo -E apt-get -y clean
+          sudo timedatectl set-timezone "$TZ"
+          sudo mkdir -p /workdir
+          sudo chown $USER:$GROUPS /workdir
+          echo "WORKFLOW_NAME=AXT-1800" | tr ' ' '_' >> $GITHUB_OUTPUT
+          echo "TAG2=${{ github.event.inputs.tag2 }}" | tr ' ' '_' >> $GITHUB_ENV
+
+
+    - name: Clone OpenWrt source code
+      working-directory: /workdir
+      run: |
+        df -hT $PWD
+        REPO_URL=$REPO_URL_IMM
+        git clone $REPO_URL --single-branch openwrt
+        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
+        cd openwrt
+        
+        # Remove Chinese mirrors from mirror file
+        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
+          if [ -f "$PROJECT_MIRRORS_FILE" ]; then
+            sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
+          fi
+        
+        git fetch --tags # Get all tags
+        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
+        
+    - name: Load custom feeds and run part 1 script
+      run: |
+        echo "WORKFLOW_NAME=AXT-1800" | tr ' ' '_' >> $GITHUB_OUTPUT
+        cat $GITHUB_OUTPUT
+        cat $GITHUB_ENV
+        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
+        chmod +x $DIY_P1_SH
+        cd openwrt
+        ./scripts/feeds update -a
+        $GITHUB_WORKSPACE/$DIY_P1_SH
+
+    - name: Install all feeds
+      run: cd openwrt && ./scripts/feeds install -a
+
+    - name: Load custom configuration and run part 2 script
+      run: |
+        echo "WORKFLOW_NAME=AXT-1800" | tr ' ' '_' >> $GITHUB_OUTPUT
+        cat $GITHUB_OUTPUT
+        [ -e $DEFAULT_SETTING ] && mv $DEFAULT_SETTING openwrt/package/default-settings
+        ls openwrt/package/
+        [ -e files ] && mv ./files openwrt/files
+        [ -e $CONFIG_FILE_IMM ] && mv $CONFIG_FILE_IMM openwrt/.config
+        chmod +x $DIY_P2_SH
+        cd openwrt
+        $GITHUB_WORKSPACE/$DIY_P2_SH
+        make defconfig
+        echo "Final diffconfig:"
+        ./scripts/diffconfig.sh    
+
+    - name: Cache Toolchain (Cache build environment)
+      uses: HiGarfield/cachewrtbuild@main
+      if: env.CACHE_TOOLCHAIN != 'false'
+      with:
+        ccache: true
+        mixkey: ${{ github.workflow }}-${{ env.REPO_BRANCH }}-${{ hashFiles(env.CONFIG_FILE_IMM, '**/scripts-part*.sh') }}
+        prefix: ${{ env.OPENWRT_PATH }}
+    
+    - name: Download packages
+      id: package
+      run: |
+         cd openwrt
+         make download -j8
+         find dl -size -1024c -exec ls -l {} \;
+         find dl -size -1024c -exec rm -f {} \;
+
+    - name: Compile firmware
+      id: compile
+      run: |
+        cd openwrt
+        echo -e "$(nproc) cores for compilation"
+        echo "y" | make -j$(expr $(nproc) + 1) || echo "y" | make -j1 V=s
+        echo "compile-status=success" >> $GITHUB_ENV
+        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+        echo "compile=success" >> $GITHUB_OUTPUT
+        if [ -s DEVICE_NAME ]; then
+          echo "device-name=$(cat DEVICE_NAME)" >> $GITHUB_OUTPUT
+        fi
+        echo "file-date=$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT
+
+    - name: Check disk space after build
+      if: (!cancelled())
+      run: df -hT
+
+    - name: Upload bin directory
+      uses: actions/upload-artifact@main
+      if: steps.compile.outputs.compile == 'success' && env.UPLOAD_BIN_DIR == 'true'
+      with:
+        name: OpenWrt_bin_${{ steps.compile.outputs.device-name }}_${{ steps.compile.outputs.file-date }}
+        path: openwrt/bin
+
+    - name: Organize firmware files
+      id: organize
+      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+      run: |
+        cd openwrt/bin/targets/*/*
+        rm -rf packages
+        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+        echo "status=success" >> $GITHUB_ENV
+        echo "organize=success" >> $GITHUB_OUTPUT
+        cat $GITHUB_ENV
+
+    - name: Upload firmware
+      uses: actions/upload-artifact@main
+      if: steps.organize.outputs.organize == 'success' && !cancelled()
+      with:
+        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+        path: ${{ env.FIRMWARE }}
+
+    - name: Generate release tag
+      id: tag
+      if: steps.compile.outputs.compile == 'success' && env.UPLOAD_RELEASE == 'true'
+      run: |
+        echo "Generating tag..."
+        CLEANED_WORKFLOW_NAME=$(echo "$WORKFLOW_NAME" | tr -c '[:alnum:]_' '-')
+        CLEANED_TAG2=$(echo "$TAG2" | tr -c '[:alnum:].-' '-')
+        BASE_TAG="${CLEANED_WORKFLOW_NAME}-${CLEANED_TAG2}"
+        DATE_SUFFIX=$(date +"%Y%m%d-%H%M")
+        RELEASE_TAG="${BASE_TAG}-${DATE_SUFFIX}"
+        if [ -z "$RELEASE_TAG" ]; then
+            echo "Error: Release tag is empty. Exiting."
+            exit 1
+        fi
+        echo "release_tag=$RELEASE_TAG" >> $GITHUB_ENV
+        touch release.txt
+        echo "tag=success" >> $GITHUB_OUTPUT
+        echo "Release Tag: $RELEASE_TAG"
+
+    - name: Release Firmware
+      uses: softprops/action-gh-release@v2
+      with:
+        tag_name: immortalwrt_gl-axt1800-nss-${{ env.release_tag }}
+        files: ${{ env.FIRMWARE }}/*
+        body: |
+          Source: ${{ env.REPO_URL_IMM }}
+
+    - name: Delete workflow runs
+      uses: GitRML/delete-workflow-runs@main
+      with:
+        retain_days: 5
+        keep_minimum_runs: 5
+  
+    - name: Remove old Releases
+      uses: dev-drprasad/delete-older-releases@v0.1.0
+      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      with:
+        keep_latest: 10
+        delete_tags: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
